package com.jun.demo;

/**
 * @author http://www.cnblogs.com/leiOOlei/p/3376155.html
 * 用Maven创建Hibernate项目
 *
 */

import java.util.Date;

/**
 * Dbuser generated by hbm2java
 */
public class Dbuser implements java.io.Serializable {

    private int userId;
    private String username;
    private String createdBy;
    private Date createdDate;

    public Dbuser() {
    }

    public Dbuser(int userId) {
        this.userId = userId;
    }

    public Dbuser(int userId, String username, String createdBy,
            Date createdDate) {
        this.userId = userId;
        this.username = username;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

}
