CREATE DATABASE `hibernate` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE TABLE `grade` (
  `GID` int(11) NOT NULL,
  `GNAME` varchar(45) DEFAULT NULL,
  `GDESC` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`GID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `student` (
  `SID` int(11) NOT NULL,
  `SNAME` varchar(45) DEFAULT NULL,
  `SEX` varchar(45) DEFAULT NULL,
  `GID` int(11) DEFAULT NULL,
  PRIMARY KEY (`SID`),
  KEY `fkn_SID_idx` (`GID`),
  CONSTRAINT `fkn_SID` FOREIGN KEY (`GID`) REFERENCES `grade` (`GID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
